Senzing/docker-g2command

Dockerfile

Same issue as https://github.com/Senzing/docker-g2loader/pull/7

issue-1 Changed ENTRYPOINT and CMD

---

Dockerfile
Makefile
README.md

ISSUE-1
Bring code upto current [docker-template](https://github.com/Senzing/docker-template) standards.

issue-1  Match G2Loader and docker-template

---

Dockerfile
README.md

issue-1 Move to senzing/senzing-base

---

.project
.pydevproject
CODE_OF_CONDUCT.md
Dockerfile
README.md
docker-compose.test.yml
rootfs/app/container-test.sh
rootfs/app/healthcheck.sh
rootfs/opt/senzing/g2/python/G2Command.py

issue-1 Pass inspectDockerImage tests

---

docker-compose.test.yml

issue-1 Use default command

---

docker-compose.test.yml

issue-1 Try to fix hanging acceptance test

---

CHANGELOG.md
Dockerfile
README.md
docs/errors.md

issue-15 Migrate to Python3

---

Dockerfile

issue-15 Pin an image version

---

Dockerfile

issue-15 Change invocation to python3

---

Dockerfile
README.md

issue-20 Make non-root container

---

CHANGELOG.md
Dockerfile

 issue-20 Make non-root container 

---

CHANGELOG.md
Dockerfile
Makefile
README.md

issue-24 Update for RPM installation

---

CHANGELOG.md
Dockerfile
README.md

issue-24 Support for RPM-based installation

---

Dockerfile
README.md

issue-24 Fix data/1.0.0

---

README.md

issue-24 Added Related artifacts

---

.dockerignore
CHANGELOG.md
Dockerfile
README.md

issue-29 Added MSSQL support. Refactored to template

---

README.md

issue-29 Refactor to template

---

CHANGELOG.md

issue-29 Fix entry

---

PULL_REQUEST_TEMPLATE.md

issue-29 Change input of issue

---

Makefile
README.md

issue-35 Refactor to template

---

CHANGELOG.md
Dockerfile

#37 Update to senzing/senzing-base:1.4.0

---

Dockerfile

#42 upgrade to senzing/senzing-base:1.5.2

---

README.md

#45 Update to senzingdata 2.0.0
